import AuthNavbar from "@/Components/AuthNavbar/AuthNavbar";
import Footer from "@/Components/Footer/Footer";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavbarComponent } from "@/Components/Navbar/NavbarComponent";


config.autoAddCss = false; // Tell Font Awesome to skip adding the CSS automatically since it's being imported above


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} style={{margin: 0, padding: 0}}>
        <NavbarComponent />
        {/* <AuthNavbar /> */}
        {/* <SessionAuthProvider> */}
          {children}
        {/* </SessionAuthProvider> */}
        <Footer />
      </body>
    </html>
  );
}
